### ISSUE TITLE
issue of getting values of accelerometer ,gyroscope

### ISSUE THREAD

**Issue by NIIHARIKARAVIPROLU** [dtornqvist/icm-20948-arduino-library#1]
Hi,
 I had changed the whole code in cc1352 . and now i am only getting accelerometer x_axis values but not getting y_axis,zaxis values  . May I know other than read sensors is there any function to be called to read all three axis values of gyroscope,accelerometer,magnetometer values

**Comment by dtornqvist** [comment]
I guess you will have to check the addresses for that data on your device. The ICM-20948 supports that all values are read at once because the values are at consecutive addresses. Maybe the cc1352 don’t.
