### ISSUE TITLE
ESP32 and ICM-20948

### ISSUE THREAD

**Issue by PGretsche** [dtornqvist/icm-20948-arduino-library#2]
Hey,
i try to hook up the ICM-20948 on the ESP32 and search for some code i can use to program it with the arduino ide. What do i have to change on this code so it´s working?

Sorry in advance for my bad english and coding skill.

**Comment by dtornqvist** [comment]
Hi,

I think you can reuse most of the code. The i2c communication must be redone and you will have to use a library available for ESP32. Otherwise I would guess that most code can be reused.
